server:
  port: 8085
  servlet:
    context-path: /babelfish-service
spring:
  application:
    name: babelfish-service
  datasource:
#    url: jdbc:mysql://localhost:3306/babelfish?createDatabaseIfNotExist=true&useSSL=false
    url: jdbc:h2:~/h2/babelfish;AUTO_SERVER=TRUE
    username: root
    password: root
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  activemq:
    broker-url: tcp://localhost:61616

logging:
  level:
    org:
      hibernate:
        type: info