package com.trabeya.engineering.babelfish.model;

public enum TextToSpeechSynthesisDeviceProfile {
    WEARABLE_CLASS_DEVICE,
    HANDSET_CLASS_DEVICE,
    HEADPHONE_CLASS_DEVICE,
    SMALL_BLUETOOTH_SPEAKER_CLASS_DEVICE,
    MEDIUM_BLUETOOTH_SPEAKER_CLASS_DEVICE,
    LARGE_HOME_ENTERTAINMENT_CLASS_DEVICE,
    LARGE_AUTOMOTIVE_CLASS_DEVICE,
    TELEPHONY_CLASS_APPLICATION
}
